import type { Metadata } from "next";
import { Tajawal } from "next/font/google";
import "./globals.css";
import { Provider } from "@/components/ui/provider";
import { LayoutSessionWrapper } from "@/components/layout-wrapper/layout-wrapper";
import { SignupProvider } from "./context/auth-context";

const tajawal = Tajawal({
  subsets: ["arabic", "latin"],
  variable: "--font-tajawal",
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl" suppressHydrationWarning>
      <body className={`${tajawal.variable}`}>
        <LayoutSessionWrapper>
        <SignupProvider>
          <Provider>{children}</Provider>
        </SignupProvider>
        </LayoutSessionWrapper>
      </body>
    </html>
  );
}
